### ISSUE TITLE
Unexpected results

### ISSUE THREAD

**Issue by pathmapper** [zsiki/realcentroid#15]
I'm getting unexpected results for some polygons which are almost rectangles:

![compare_centroid_realcentroid](https://user-images.githubusercontent.com/20856381/65852125-85524f00-e355-11e9-917b-fc13be378b8c.png)

The red dot are the centroids calculated using the `realcentroid` plugin. Except two, these are not looking like centroids. 
I would expect something like the green dots, which are calculated using the standard QGIS `Centroids` tool.

The polygon vertices are located where the black dots are. Here is a sample shapefile with the polygons used: [test_centroid.zip](https://github.com/zsiki/realcentroid/files/3669013/test_centroid.zip)

`Point on surface` tool gives the same result as `realcentroid` plugin.

Any idea what's going on?

**Comment by zsiki** [comment]
RealCentroid uses Point on surface, so I am not surprised about the result. The big difference between Centroid and PointonSurface is:
Centroid returns weight point of vertices and it can be outside the polygon, that was the reason to write realcentroid some years ago when even Point on surface was not available from Python in QGIS. Nowadays in QGIS 3 there is no need for my plug-in you can use processing to get the same result. If you have convex polygons then you can use centroid also to get an internal point.

**Comment by pathmapper** [comment]
Thanks @zsiki

> in QGIS 3 there is no need for my plug-in

In QGIS 3 I still prefer your plugin over `Point on surface` for some use cases, because it doesn't fail if there are invalid geometries. Instead `realcentroid` gives a warning and creates a centroid for the valid geometries.
