### ISSUE TITLE
Please consider moving this to Processing

### ISSUE THREAD

**Issue by pcav** [zsiki/realcentroid#5]
As a submodule, so it can be used in more complex workflow

**Comment by zsiki** [comment]
After QGIS 2.4 this plugin has lesser relevance, the GEOS pointOnSurface function has been bound to Python QgsGeometry.poinOnSurface.  Changing the Vector/Geometry Tools/Polygon Centroid to use pointOnSurface instread of centroid function is another alternative to integrate this plugin  into QGIS.
I'll check how to create a new toolbox algorithm. Thanks.

**Comment by zsiki** [comment]
I've created a processing python script from the plugin code, it can be found in realcentroid_algorithm.py.
Is there a repository to collect these scripts?

**Comment by pcav** [comment]
https://github.com/qgis/QGIS-Processing
@volaya

**Comment by zsiki** [comment]
Thanks Paolo, I've made a pull request.
