### ISSUE TITLE
AttributeError : 'Ui_RealCentroid' object has no attribute 'selectedBox'

### ISSUE THREAD

**Issue by DelazJ** [zsiki/realcentroid#6]
Hi,
while running RealCentroids plugin (v 0.5), you get the error message in the title. It can be solved by recreating the ui_realcentroid.py file with pyuic4 command.

Another minor issue is that the name displayed in Plugins menu is 'realcnetroid' instead of 'realcentroid'

**Comment by zsiki** [comment]
Dear DelazJ,

thanks you reporting issue.
I've fixed it.

Zoltan

**Comment by DelazJ** [comment]
Nice...
Thank you for the plugin...

Envoyé depuis mon HTC

----- Reply message -----
De : "Zoltan Siki" <notifications@github.com>
Pour : "zsiki/realcentroid" <realcentroid@noreply.github.com>
Cc : "DelazJ" <delazj@gmail.com>
Objet : [realcentroid] AttributeError : 'Ui_RealCentroid' object has no attribute 'selectedBox' (#6)
Date : lun., janv. 26, 2015 23:51

Dear DelazJ,



thanks you reporting issue.

I've fixed it.



Zoltan



On Mon, 26 Jan 2015, DelazJ wrote:



> Hi,

> while running RealCentroids plugin (v 0.5), you get the error message in the title. It can be solved by recreating the ui_realcentroid.py file with pyuic4 command.

>

> Another minor issue is that the name displayed in Plugins menu is 'realcnetroid' instead of 'realcentroid'

>

> ---

> Reply to this email directly or view it on GitHub:

> https://github.com/zsiki/realcentroid/issues/6

&mdash;
